version: '3.8'

services:
  kong-db:
    image: postgres:13
    container_name: kong-db
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    networks:
      - esd-net

  kong-migration:
    image: kong:3.9
    container_name: kong-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
    networks:
      - esd-net
    depends_on:
      - kong-db

  kong:
    image: kong:3.9
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_MANAGER_LISTEN: 0.0.0.0:8002
    ports:
      - "8000:8000" # Proxy 
      - "8001:8001" # Admin API
      - "8002:8002" # Kong Manager GUI
    networks:
      - esd-net
    depends_on:
      - kong-migration

volumes:
  kong_data:

networks:
  esd-net:
    external: true
    name: esd_esd-net 